### ISSUE TITLE
firebase-performance 

### ISSUE THREAD

**Issue by christophe-g** [firebase/firebase-bower#2]
Aware this repo is not regularly monitored for issues. Still reporting here as more convenient. 

Should firebase-performance.js not be part of this sdk ?

**Comment by samtstern** [comment]
@Feiyang1 wdyt?

**Comment by Feiyang1** [comment]
Good catch. We should add firebase-performance.js here. Will fix in the next release.

**Comment by jhuleatt** [comment]
fixed! thanks all
