### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by hippee-lee** [firebase/firebase-bower#3]
FYI: 

I just updated my project to 
 $ bower cache list firebase   
firebase=git://github.com/firebase/firebase-bower.git#1.0.21
firebase=git://github.com/firebase/firebase-bower.git#1.0.22

when my tests run that use angularfire / firebase I get this:
PhantomJS 1.9.7 (Mac OS X) ERROR
  TypeError: 'undefined' is not a function (near '...;E.Context=Y;}).bind(this)();...')
  at /Users/matt_hippely/git/vn-toolbox-common/app/bower_components/firebase/firebase.js:159

Please let me know if I can provide more or better feedback to recreate the issue.

**Comment by mikelehen** [comment]
I believe this was fixed quite a while ago.  If you're still able to reproduce this, can you please contact support@firebase.com.  Thanks!
