### ISSUE TITLE
Missing Firebase Analytics

### ISSUE THREAD

**Issue by gvsrepins** [firebase/firebase-bower#3]
The module Firebase Analytics is missing.

Check the reference file at https://www.gstatic.com/firebasejs/7.0.0/firebase-analytics.js.

**Comment by gvsrepins** [comment]
Guys, can you please update the repository with the new firebase modules?
I'm particularly interested in the analytics one.

Thanks in advance!

**Comment by gvsrepins** [comment]
I have made this PR #4 to fix it. Please merge. 

Thanks!

**Comment by gvsrepins** [comment]
@hsubox76 please check this.

**Comment by christophe-g** [comment]
+1 
Would be great to have this and #2 sorted out.

**Comment by jhuleatt** [comment]
fixed! thanks all

**Comment by christophe-g** [comment]
@jhuleatt - Thank you  ; )
