### ISSUE TITLE
Firebase.onAuth() to return user's UID

### ISSUE THREAD

**Issue by julesbou** [firebase/firebase-bower#4]
I'm using following code to create a user:

```
var onComplete = function(err) {};
ref.createUser({ ... }, onComplete);
```

Then i'm looking for a way to access my new user's UID the simplest way possible (preferably without having to logging him). Would it be possible to include UID as the second argument of `onComplete` ?

**Comment by robertdimarco** [comment]
@julesbou This is now available in the Firebase Web client >= v2.0.5. You can now get the user id via the following:

```javascript
ref.createUser({ ... }, function(err, user) {
  if (user) { 
    console.log('Successfully created user with id', user.uid);
  }
}
```
