### ISSUE TITLE
Error: You are using macOS 10.11

### ISSUE THREAD

**Issue by callsSolve** [firebase/firebase-bower#6]
Error: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this old version.

HTMLs-MBP:~ html$ 
HTMLs-MBP:~ html$ 
HTMLs-MBP:~ html$ sudo port install yarn
Password:
sudo: port: command not found
HTMLs-MBP:~ html$

**Comment by callsSolve** [comment]
Please I need help with my ongoing issues...

**Comment by shauryaaher** [comment]
Hey, this repo is autogenerated and doesn't suppert PRs and issues. Contact [Firebase Support](https://firebase.google.com/support) for bugs etc.

**Comment by morganchen12** [comment]
@callsSolve you're running into a homebrew error, please seek out homebrew support.
