### ISSUE TITLE
password logging in plain text in ie11 console

### ISSUE THREAD

**Issue by jshortall** [firebase/firebase-bower#7]
I stumbled across a good one! 

I might be doing something wrong on my end, but when I log in with Firebase Email and Password Auth in IE11, IE puts a "Message" in the console describing the https request that shows the querystring with my password in plain text! Is there a way to fix this so it doesn't happen?

![firebase_console_error](https://cloud.githubusercontent.com/assets/8116396/5545274/36fb3424-8aeb-11e4-9388-1f9122f63620.jpg)

Loving your work, just trying to nail out a few details to make it production ready. Thanks for your help!

**Comment by mikelehen** [comment]
Hey.  Thanks for the feedback!

Unfortunately, this is working as expected.  It's a bit unfortunate that IE is logging the request to the console, but be aware that the request is sent over HTTPS, so the password is never sent in the clear, and your users likely won't have the console open, so they won't see the password there.

We do agree that it'd be better if the password never appeared in cleartext anywhere.  We might look into implementing SRP (http://srp.stanford.edu/) or similar in the future, but at this time, the behavior you are seeing is expected.  Sorry!
